### ISSUE TITLE
raise NotImplementedError

### ISSUE THREAD

**Issue by keithmgould** [hardmaru/estool#21]
Hello!

I'm running python 3.6 over miniconda on Mac 10.14

versions:
```
gym: 0.10.4
cma: 2.6.0
pybullet: 2.2.2
```

I'm able to run the BipedalWalker-v2 env on its own with a mini test script:

```
import gym
env = gym.make('BipedalWalker-v2')
env.reset()
for t in range(1000):
    env.render()
    observation, reward, done, info = env.step(env.action_space.sample()) # take a random action
    if done:
      break
```

So given the above, I know gym and the env are working fine.

Also I'm able to train with the estool just fine using the bullet racecar env. I'm also able to run the trained model from bullet racecar.

What does *not* work is training with the BipedalWalker-v2 env.

Here is the command I run: `python train.py biped -n 1 -t 2`
(same results for when n=8 and t=4)

And here are the results:

```
(py36) Keiths-MacBook-Pro:estool keithgould$ p train.py biped -n 1 -t 2
pybullet build time: Sep 26 2018 10:51:37
current_dir=/Users/keithgould/miniconda3/envs/py36/lib/python3.6/site-packages/pybullet_envs/bullet
['mpirun', '-np', '2', '/Users/keithgould/miniconda3/envs/py36/bin/python3', 'train.py', 'biped', '-n', '1', '-t', '2']
pybullet build time: Sep 26 2018 10:51:37
pybullet build time: Sep 26 2018 10:51:37
current_dir=/Users/keithgould/miniconda3/envs/py36/lib/python3.6/site-packages/pybullet_envs/bullet
current_dir=/Users/keithgould/miniconda3/envs/py36/lib/python3.6/site-packages/pybullet_envs/bullet
assigning the rank and nworkers 2 0
assigning the rank and nworkers 2 1
making model from game: Game(env_name='BipedalWalker-v2', time_factor=0, input_size=24, output_size=4, layers=[40, 40], activation='tanh', noise_bias=0.0, output_noise=[False, False, False])
making model from game: Game(env_name='BipedalWalker-v2', time_factor=0, input_size=24, output_size=4, layers=[40, 40], activation='tanh', noise_bias=0.0, output_noise=[False, False, False])
size of model 2804
size of model 2804
(1,2mirr1)-aCMA-ES (mu_w=1.0,w_1=100%) in dimension 2804 (seed=364359, Tue Nov 27 12:07:55 2018)
('process', 0, 'out of total ', 2, 'started')
('training', 'biped')
('population', 2)
('num_worker', 1)
('num_worker_trial', 2)


(1,2mirr1)-aCMA-ES (mu_w=1.0,w_1=100%) in dimension 2804 (seed=385130, Tue Nov 27 12:07:55 2018)
('process', 1, 'out of total ', 2, 'started')

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
sweet, loaded the env.
<BipedalWalker instance>
cool right??
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
sweet, loaded the env.
<BipedalWalker instance>
cool right??
Traceback (most recent call last):
  File "train.py", line 448, in <module>
    main(args)
  File "train.py", line 404, in main
    slave()
  File "train.py", line 229, in slave
    fitness, timesteps = worker(weights, seed, train_mode, max_len)
  File "train.py", line 205, in worker
    train_mode=train_mode, render_mode=False, num_episode=num_episode, seed=seed, max_len=max_len)
  File "/Users/keithgould/Robotics/estool/model.py", line 258, in simulate
    obs, reward, done, info = model.env.step(action)
  File "/Users/keithgould/miniconda3/envs/py36/lib/python3.6/site-packages/gym/core.py", line 63, in step
    raise NotImplementedError
NotImplementedError
```

There are some print statements in there where I'm trying to figure out why the `step` function is not defined (causing the NotImplementedError). 

As far as I can tell the environment is loaded, and I know it has a step function...

Any thoughts/help appreciated.

Keith

**Comment by hardmaru** [comment]
Hi!

Thanks for the message. I’m going to edit the readme to state which
versions of gym and bullet I used when I first released the code.

Gym has changed quite a bit since then I think

**Comment by keithmgould** [comment]
Ok, thank you. I'm under the impression that bullet should not matter in this case, as its not a bullet env. But please correct me if wrong?

I can't tell now if it's something about gym versioning, or if its something else. I wonder if you would get the same error with BipedalWalker-v2 today on you system?

I should have mentioned the versions of gym (and bullet) in the above, I'll edit the above to add.

Thank you again!!

**Comment by keithmgould** [comment]
Verified that it works with Gym 0.9.4. Thank you! Closing this.

**Comment by danbri** [comment]
> pip install gym==0.9.4
also fixed it for me
